package:
  name: shift-miscutils
  version: "2.1.0"

source:
  git_url: git@github.com:hanlonlab/shift-foundry.git
  git_rev: rate_limited_cc

build:
  include_recipe: False

about:
  home: https://github.com/hanlonlab/shift-foundry
