package:
  name: shift-coreclient
  version: "1.5.0"

source:
  git_url: https://github.com/hanlonlab/shift-main.git

requirements:
  build:
    - libcurl
    - quickfix
    - shift-miscutils
  run:
    - libcurl
    - quickfix
    - shift-miscutils

build:
  include_recipe: False

about:
  home: https://github.com/hanlonlab/shift-main
